### ISSUE TITLE
Emoji filter doesn't remove animated emotes

### ISSUE THREAD

**Issue by 0x1452** [ajuelosemmanuel/wysi-bot#1]
The following line is supposed to filter out emotes:

https://github.com/ajuelosemmanuel/wysi-bot/blob/2afd90ad8a30601791d8c8f6d877d2211d295dcc/main.py#L44

However, it doesn't handle animated emotes with the format `<a:name:ID>`.
I suggest updating the regex to `<a?:\w*:\d*>`.

**Comment by ajuelosemmanuel** [comment]
Hello,
Thank you very much for helping me !
I'll update the bot asap !
